### ISSUE TITLE
What's the version of pytorch? cpu or gpu?

### ISSUE THREAD

**Issue by bb0928** [YanjieZe/rl3d#4]
when solving the environment, i encountered some problem.
I followed the instruction at first, but failed to install "gym", i thus followed a closed issue mentioned previously.
but after that, when i typed "bash scripts/train.sh", the output are as follow:
TYPE  state+image
Found 1 GPUs for rendering. Using device 0.
camera traj len: 50
Working directory: logs/robot_reach/sacv2_3d/default/0
Traceback (most recent call last):
  File "src/train.py", line 240, in <module>
    main(args) 
  File "src/train.py", line 104, in main
    assert torch.cuda.is_available(), 'must have cuda enabled'
AssertionError: must have cuda enabled
I am now wondering if i have installed the right version of pytorch.
Could you offer any help or instructions about that? many thanks!

**Comment by bb0928** [comment]
Supplement:
(rl3d) user@user-System-Product-Name:~/rl3d-main$ conda list pytorch
# packages in environment at /home/user/miniconda3/envs/rl3d:
#
# Name                    Version                   Build  Channel
pytorch                   2.1.0           cpu_py38hab5cca8_0    defaults

**Comment by bb0928** [comment]
![image](https://github.com/user-attachments/assets/bcc5e39d-91ab-4a5d-8ea5-e98ae76bdfd3)

**Comment by bb0928** [comment]
I have updated my torch to gpu version and it works.
